twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig'] # thème de formulaire livré avec Symfony

when@test:
    twig:
        strict_variables: true
